### ISSUE TITLE
Build on Windows with GCC? 

### ISSUE THREAD

**Issue by 3oheicrw** [rmottola/Arctic-Fox#89]
I don't want to use MSVC. GCC now also has UCRT64 support apart from traditional MSVCRT. Could you make it possible to build on Windows using GCC?

The GCC I got is from there: https://winlibs.com/

**Comment by rmottola** [comment]
I don't build on windows, roytam builds with MSVC.
Firefox had support for building with mingw builds as Tier 3 and Arcticfox code base is old enough that gcc still fully works.
You are on your own though to reconstruct how it did work. I would suggest installing ming32 and/or ming64 and starting to see how far you go. Look for documentation on building Firefox on windows of the 40-45 version aera, since that is about the status of our build system..
There might be patches or fixes missing, in that I can try to help and see if I can backport them,.

**Comment by rmottola** [comment]
I pulled in recently some specific windows gcc fixes, you might try.

**Comment by rmottola** [comment]
@3oheicrw did you retry perhaps? I commited some possibly related fixes to that, try dev branch.

**Comment by 3oheicrw** [comment]
> @3oheicrw did you retry perhaps? I commited some possibly related fixes to that, try dev branch.

No my friend. Sorry. I tried to install VS Build Tools 2022 on my Windows 7 and it pretty much destroyed my system after I uninstalled it due to all sort of missing DLL errors. Only the VC++ AIO runtime that saved me. Now I have VS Build Tools 2015 installed and it works :smile:

**Comment by 3oheicrw** [comment]
I will try to build with GCC as soon as I can and report back to you. I have to uninstall VS Build Tools first because my SSD is small.

**Comment by 3oheicrw** [comment]
@rmottola No hope friend. Fail immediately because compiler can't create executable, it's still insisting the compiler is VS Studio's cl.exe. I use start-shell.bat which doesn't have any VS environment already setup. I already added mingw64/bin to PATH and which gcc tells correctly where gcc.exe is. I think we should just close this issue and give up on this.

**Comment by rmottola** [comment]
Do you reopen because you have news? I did trickle in some windows related things, but didn't test them.

**Comment by 3oheicrw** [comment]
> Do you reopen because you have news? I did trickle in some windows related things, but didn't test them.

Trying to build. There is encoding errors with the Python 2 scripts on MSYS2 that I have no idea how to fix. So it seems Mozilla Build has to be used instead.

**Comment by 3oheicrw** [comment]
Here is the error printed on MSYS2:

```
$ ./mach build
Traceback (most recent call last):
  File "./mach", line 148, in <module>
    main(sys.argv[1:])
  File "./mach", line 80, in main
    sys.exit(mach.run(args))
  File "C:/build/python/mach/mach/main.py", line 347, in run
    self._print_error_header(argv, sys.stdout)
  File "C:/build/python/mach/mach/main.py", line 479, in _print_error_header
    fh.write('Error running mach:\n\n')
LookupError: unknown encoding: cp65001
```

I have Python 2 (mingw-w64-x86_64-python2) installed.

**Comment by 3oheicrw** [comment]
This is my .mozconfig:

```
export CC="gcc"
export CXX="g++"
ac_add_options --target=x86_64-w64-mingw32
ac_add_options --host=x86_64-w64-mingw32
mk_add_options MOZ_CO_PROJECT=browser
ac_add_options --enable-application=browser
ac_add_options --enable-optimize="-O2"
ac_add_options --enable-jemalloc
ac_add_options --enable-shared-js
ac_add_options --enable-devtools
```

**Comment by 3oheicrw** [comment]
On Mozilla Build 2.1, gcc and g++ now correctly picked up but it error with a faulty test for C++11:

```
 0:00.36 c:\mozilla-build\mozmake\mozmake.EXE -f client.mk -s
 0:16.17 Adding client.mk options from c:/build/.mozconfig:
 0:16.17     CONFIG_GUESS=x86_64-w64-mingw32
 0:16.17     MOZ_CO_PROJECT=browser
 0:16.17     MOZ_OBJDIR=c:/build/obj-x86_64-w64-mingw32
 0:16.17     OBJDIR=c:/build/obj-x86_64-w64-mingw32
 0:16.17     FOUND_MOZCONFIG=c:/build/.mozconfig
 0:16.17 cd c:/build/obj-x86_64-w64-mingw32
 0:16.17 c:/build/configure
 0:16.17 Adding configure options from c:/build/.mozconfig
 0:16.17   --target=x86_64-w64-mingw32
 0:16.17   --host=x86_64-w64-mingw32
 0:16.17   --enable-application=browser
 0:16.17   --enable-optimize=-O2
 0:16.17   --enable-jemalloc
 0:16.17   --enable-shared-js
 0:16.17   --enable-devtools
 0:16.17 loading cache ./config.cache
 0:16.17 checking host system type... x86_64-w64-mingw32
 0:16.17 checking target system type... x86_64-w64-mingw32
 0:16.17 checking build system type... x86_64-w64-mingw32
 0:16.17 checking for mawk... no
 0:16.17 checking for gawk... gawk
 0:16.17 checking for python2.7... /c/mozilla-build/python/python2.7
 0:16.17 Creating Python environment
 0:16.17 checking Python environment is Mozilla virtualenv... yes
 0:16.17 checking for perl5... no
 0:16.17 checking for perl... /usr/bin/perl
 0:16.17 checking for gcc... gcc
 0:16.17 checking whether the C compiler (gcc  ) works... yes
 0:16.17 checking whether the C compiler (gcc  ) is a cross-compiler... no
 0:16.17 checking whether we are using GNU C... yes
 0:16.17 checking whether gcc accepts -g... yes
 0:16.17 checking for c++... g++
 0:16.17 checking whether the C++ compiler (g++  ) works... yes
 0:16.17 checking whether the C++ compiler (g++  ) is a cross-compiler... no
 0:16.17 checking whether we are using GNU C++... yes
 0:16.17 checking whether g++ accepts -g... yes
 0:16.17 checking for ranlib... ranlib
 0:16.17 checking for ml64... no
 0:16.17 checking for as... /c/mingw64/bin/as
 0:16.17 checking for ar... ar
 0:16.17 checking for ld... ld
 0:16.17 checking for strip... strip
 0:16.17 checking for windres... windres
 0:16.17 checking for otool... no
 0:16.17 checking for rustc... no
 0:16.17 checking for w32api version >= 3.14... yes
 0:16.17 checking for windres version >= 2.14.90... (Binutils
 0:16.17 c:/build/configure: line 4879: test: (Binutils: integer expression expected
 0:16.17 checking for x86_64-w64-mingw32-widl... midl
 0:16.17 checking for Windows SDK being recent enough... yes
 0:16.17 checking how to run the C preprocessor... gcc -E -nologo
 0:16.17 checking how to run the C++ preprocessor... g++ -TP -E -nologo
 0:16.17 checking for a BSD compatible install... /usr/bin/install -c
 0:16.17 checking whether ln -s works... no
 0:16.17 checking for minimum required perl version >= 5.006... 5.008008
 0:16.17 checking for full perl installation... yes
 0:16.17 checking for doxygen... /c/mingw64/bin/doxygen
 0:16.17 checking for autoconf... /usr/bin/autoconf
 0:16.17 checking for unzip... /c/mozilla-build/info-zip/unzip
 0:16.17 checking for zip... /c/mozilla-build/info-zip/zip
 0:16.17 checking for xargs... /usr/bin/xargs
 0:16.17 checking for rpmbuild... :
 0:16.17 checking for c:/mozilla-build/mozmake/mozmake.EXE... c:/build/configure: line 5748: test: /usr/local/bin/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/7zip/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/info-zip/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/kdiff3/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/mozmake/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/nsis-3.0b1/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/nsis-2.46u/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/python/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/python/Scripts/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/upx391w/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/wget/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/yasm/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: ./c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /usr/local/bin/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /usr/mingw/bin/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /usr/bin/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/Windows/System32/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/Windows/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/Windows/System32/Wbem/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mozilla-build/moztools-x64/bin/c: binary operator expected
 0:16.17 c:/build/configure: line 5748: test: /c/mingw64/bin/c: binary operator expected
 0:16.17 no
 0:16.17 checking for make... /usr/local/bin/make
 0:16.17 checking for X... no
 0:16.17 checking that static assertion macros used in autoconf tests work... yes
 0:16.17 checking for --noexecstack option to as... no
 0:16.17 checking for -z noexecstack option to ld... no
 0:16.17 checking for -z text option to ld... no
 0:16.17 checking for --build-id option to ld... yes
 0:16.17 checking for --ignore-unresolved-symbol option to ld... yes
 0:16.17 checking if toolchain supports -mssse3 option... yes
 0:16.17 checking if toolchain supports -msse4.1 option... yes
 0:16.17 checking for x86 AVX2 asm support in compiler... yes
 0:16.17 checking whether the C++ compiler supports -Wno-unused-local-typedef... no
 0:16.17 checking whether the C++ compiler supports -Wno-inline-new-delete... no
 0:16.17 checking whether the C++ compiler supports -Wno-unused-local-typedef... (cached) no
 0:16.17 checking whether ld has archive extraction flags... yes
 0:16.17 checking for 64-bit OS... yes
 0:16.17 checking whether the C compiler supports -Wno-format... yes
 0:16.17 checking whether the C++ compiler supports -Wno-format... yes
 0:16.17 checking whether the C++ compiler (g++ -mwindows  -fno-exceptions -fno-strict-aliasing -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2 -mms-bitfields -fno-rtti  -Wl,--build-id -static) actually is a C++ compiler... yes
 0:16.17 which: ld.gold: unknown command
 0:16.17 checking for ANSI C header files... no
 0:16.17 checking for working const... yes
 0:16.17 checking for mode_t... no
 0:16.17 checking for off_t... no
 0:16.17 checking for pid_t... no
 0:16.17 checking for size_t... no
 0:16.17 checking for gcc c++0x headers bug without rtti... yes
 0:16.17 configure: error: Your toolchain does not support C++0x/C++11 mode properly. Please upgrade your toolchain
 0:16.17 ------ config.log ------
 0:16.17       |            ^~~~
 0:16.17 confdefs.h:31:15: error: declaration does not declare anything [-fpermissive]
 0:16.17    31 | #define off_t long
 0:16.17       |               ^~~~
 0:16.17 In file included from c:\mingw64\x86_64-w64-mingw32\include\pthread.h:64,
 0:16.17                  from c:\mingw64\include\c++\12.2.0\x86_64-w64-mingw32\bits\gthr-default.h:35,
 0:16.17                  from c:\mingw64\include\c++\12.2.0\x86_64-w64-mingw32\bits\gthr.h:148,
 0:16.17                  from c:\mingw64\include\c++\12.2.0\ext\atomicity.h:35,
 0:16.17                  from c:\mingw64\include\c++\12.2.0\bits\shared_ptr_base.h:61,
 0:16.17                  from c:\mingw64\include\c++\12.2.0\bits\shared_ptr.h:53,
 0:16.17                  from c:\mingw64\include\c++\12.2.0\memory:77:
 0:16.17 c:\mingw64\x86_64-w64-mingw32\include\sys\types.h:77:9: error: multiple types in one declaration
 0:16.17    77 | typedef _mode_t mode_t;
 0:16.17       |         ^~~~~~~
 0:16.17 confdefs.h:30:16: error: declaration does not declare anything [-fpermissive]
 0:16.17    30 | #define mode_t int
 0:16.17       |                ^~~
 0:16.17 configure: failed program was:
 0:16.17 #line 11018 "configure"
 0:16.17 #include "confdefs.h"
 0:16.17 #include <memory>
 0:16.17 int main() {
 0:16.17 
 0:16.17 ; return 0; }
 0:16.17 configure: error: Your toolchain does not support C++0x/C++11 mode properly. Please upgrade your toolchain
 0:16.17 *** Fix above errors and then restart with\
 0:16.17                "c:/mozilla-build/mozmake/mozmake.EXE -f client.mk build"
 0:16.17 c:/build/client.mk:360: recipe for target 'configure' failed
 0:16.17 mozmake.EXE[2]: *** [configure] Error 1
 0:16.17 c:/build/client.mk:374: recipe for target 'c:/build/obj-x86_64-w64-mingw32/Makefile' failed
 0:16.17 mozmake.EXE[1]: *** [c:/build/obj-x86_64-w64-mingw32/Makefile] Error 2
 0:16.17 client.mk:171: recipe for target 'build' failed
 0:16.17 mozmake.EXE: *** [build] Error 2
 0:16.18 0 compiler warnings present.
```

Please note I'm using GCC 12.2.0 so it's impossible that it's not supporting C++11. I checked client.mk but found nothing about C++11.

**Comment by 3oheicrw** [comment]
I tried with Mozilla Build 3.3 upstream Pale Moon is using, this failed with Python environment is not sane:

```
 0:00.35 c:\mozilla-build\bin\mozmake.EXE -f client.mk -s
 0:06.68 Adding client.mk options from c:/build/.mozconfig:
 0:06.68     CONFIG_GUESS=x86_64-w64-mingw32
 0:06.68     MOZ_CO_PROJECT=browser
 0:06.68     MOZ_OBJDIR=c:/build/obj-x86_64-w64-mingw32
 0:06.68     OBJDIR=c:/build/obj-x86_64-w64-mingw32
 0:06.68     FOUND_MOZCONFIG=c:/build/.mozconfig
 0:06.68 cd c:/build/obj-x86_64-w64-mingw32
 0:06.68 c:/build/configure
 0:06.68 Adding configure options from c:/build/.mozconfig
 0:06.68   --target=x86_64-w64-mingw32
 0:06.68   --host=x86_64-w64-mingw32
 0:06.68   --enable-application=browser
 0:06.68   --enable-optimize=-O2
 0:06.68   --enable-jemalloc
 0:06.68   --enable-shared-js
 0:06.68   --enable-devtools
 0:06.68 loading cache ./config.cache
 0:06.68 checking host system type... x86_64-w64-mingw32
 0:06.68 checking target system type... x86_64-w64-mingw32
 0:06.68 checking build system type... x86_64-w64-mingw32
 0:06.68 checking for mawk... no
 0:06.68 checking for gawk... gawk
 0:06.68 checking for python2.7... /c/mozilla-build/python/python2.7
 0:06.68 Creating Python environment
 0:06.68 checking Python environment is Mozilla virtualenv... Traceback (most recent call last):
 0:06.68   File "<string>", line 1, in <module>
 0:06.68   File "c:\build\python\mozbuild\mozbuild\base.py", line 8, in <module>
 0:06.68     import logging
 0:06.68   File "c:\mozilla-build\python\Lib\logging\__init__.py", line 26, in <module>
 0:06.68     import sys, os, time, cStringIO, traceback, warnings, weakref, collections
 0:06.68   File "c:\mozilla-build\python\Lib\weakref.py", line 14, in <module>
 0:06.68     from _weakref import (
 0:06.68 ImportError: cannot import name _remove_dead_weakref
 0:06.68 configure: error: Python environment does not appear to be sane.
 0:06.68 ------ config.log ------
 0:06.68 This file contains any messages produced by compilers while
 0:06.68 running configure, to aid debugging if configure makes a mistake.
 0:06.68 
 0:06.68 configure:1173: checking host system type
 0:06.68 configure:1194: checking target system type
 0:06.68 configure:1212: checking build system type
 0:06.68 configure:1292: checking for mawk
 0:06.68 configure:1292: checking for gawk
 0:06.68 configure:1376: checking for python2.7
 0:06.68 configure:1486: checking Python environment is Mozilla virtualenv
 0:06.68 configure: error: Python environment does not appear to be sane.
 0:06.68 *** Fix above errors and then restart with\
 0:06.68                "c:/mozilla-build/bin/mozmake.EXE -f client.mk build"
 0:06.68 mozmake.EXE[2]: *** [c:/build/client.mk;362: configure] Error 1
 0:06.68 mozmake.EXE[1]: *** [c:/build/client.mk;374: c:/build/obj-x86_64-w64-mingw32/Makefile] Error 2
 0:06.68 mozmake.EXE: *** [client.mk;171: build] Error 2
 0:06.74 0 compiler warnings present.
```

**Comment by 3oheicrw** [comment]
Well, it seems the configure script is just too old. Normally such error will be fixed by regenerating the configure script with a newer autotools version. We stuck with autoconf2.13 too. Don't know how upstream Pale Moon and Mozilla fixed this (they stuck with autoconf2.13 too).

**Comment by 3oheicrw** [comment]
I have no knowledge about Mozilla build system. I just followed the guide and most of the time it worked. It's when using official supported environments that GCC on Windows is not. The error message said about config.log various times but I can't find this file. Since I have a bit experience with autotools maybe I could find out what's going on. My adventure with this should be ended here, but please let the issue open so someday someone could picked it up if they wanted. Goodbye.

**Comment by roytam1** [comment]
> 0:16.17 confdefs.h:31:15: error: declaration does not declare anything [-fpermissive]
>  0:16.17    31 | #define off_t long

GCC 12 is too new to AF. you really need to try GCC 4.6/4.7 for this.

**Comment by 3oheicrw** [comment]
> > 0:16.17 confdefs.h:31:15: error: declaration does not declare anything [-fpermissive]
> > 0:16.17    31 | #define off_t long
> 
> GCC 12 is too new to AF. you really need to try GCC 4.6/4.7 for this.

Nowawayds it's really difficult to get that version of GCC. But, you could make it build with Clang on FreeBSD, why do it's just weird on Windows?

**Comment by rmottola** [comment]
I don't know if the msys build is intended to be used with python or mozilla build. I suppose that if you use visual studio you use msvc, with msys gcc.
We are stuck with autoconf2.13 and this *never* changed in Firefox, they just gradually reduced its usage switching to custom stuff. Python 2.7 was needed in Firefox until recent times too, I think, quite recent. I see and have imported some commits that appear to add support for Python 3, but never tried and if Mozilla switched over years later... there must be some reason.

About GCC, I think tgat gcc 4.6/4.7 is too old. For a long time gcc 4.8 was the best compiler (should still work) and was the one supported by PM27. Gcc 6.x series is best apparently and I was able to import some fixes which allow newer versions of GCC and Clang.

On Linux I am able to build with gcc 12.2 now! Just need to disable certain optimizations or the executable is crashy. I wonder what changes with msys2 though, I am not expert there.
Please attempt to build the "dev" branch, it contains some build fixes, but I don't think they will help you.

**Comment by 3oheicrw** [comment]
> I don't know if the msys build is intended to be used with python or mozilla build. I suppose that if you use visual studio you use msvc, with msys gcc. We are stuck with autoconf2.13 and this _never_ changed in Firefox, they just gradually reduced its usage switching to custom stuff. Python 2.7 was needed in Firefox until recent times too, I think, quite recent. I see and have imported some commits that appear to add support for Python 3, but never tried and if Mozilla switched over years later... there must be some reason.
> 
> About GCC, I think tgat gcc 4.6/4.7 is too old. For a long time gcc 4.8 was the best compiler (should still work) and was the one supported by PM27. Gcc 6.x series is best apparently and I was able to import some fixes which allow newer versions of GCC and Clang.
> 
> On Linux I am able to build with gcc 12.2 now! Just need to disable certain optimizations or the executable is crashy. I wonder what changes with msys2 though, I am not expert there. Please attempt to build the "dev" branch, it contains some build fixes, but I don't think they will help you.

Could you share your .mozconfig?

**Comment by rmottola** [comment]
My mozconfig on linux is:

```
export CC="gcc  -march=westmere -mtune=westmere"
export CXX="g++ -march=westmere -mtune=westmere"

mk_add_options MOZ_MAKE_FLAGS="-s -j12"

ac_add_options --enable-accessibility
#ac_add_options --enable-gold
ac_add_options --disable-crashreporter
ac_add_options --disable-tests
#ac_add_options --enable-debug
ac_add_options --disable-debug
ac_add_options --disable-updater
ac_add_options --disable-mozril-geoloc
ac_add_options --enable-webrtc
ac_add_options --disable-safe-browsing
ac_add_options --disable-parental-controls
#ac_add_options --enable-release
ac_add_options --disable-necko-wifi
ac_add_options --disable-eme
ac_add_options --disable-gamepad
ac_add_options --disable-dbus
ac_add_options --disable-gio
ac_add_options --disable-pulseaudio
ac_add_options --disable-gstreamer
#ac_add_options --enable-strip
#ac_add_options --enable-install-strip
ac_add_options --enable-application=browser
ac_add_options --with-branding=browser/branding/arcticfox
#ac_add_options --enable-optimize="-O3 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"
ac_add_options --enable-optimize="-O2 -fno-delete-null-pointer-checks -fno-lifetime-dse -fno-schedule-insns2"

# System libraries
#ac_add_options --with-system-nspr
#ac_add_options --with-system-nss
ac_add_options --with-system-icu
```

you may want to disable gstreamer perhaps, the optimization flags are needed for gcc6 and higher to avoid crashes (do not interfere with configure)

**Comment by rmottola** [comment]
I don't know if the configure script is buggy or your toolchain is really problematic... hard to say.

In any case, today I imported certain libstc++ specific configure checks right for toolchain, you may want to retest!

**Comment by 3oheicrw** [comment]
> I don't know if the configure script is buggy or your toolchain is really problematic... hard to say.
> 
> In any case, today I imported certain libstc++ specific configure checks right for toolchain, you may want to retest!

I just followed the instruction to build on Windows. The only different is I don't use MSVC but use GCC instead.

But, if I don't use the mozilla-build environment like the document said and use MSYS2 shell directly, I faced with this error. Perhaps I posted too many comments so you ignored it:

> There is encoding errors with the Python 2 scripts on MSYS2 that I have no idea how to fix.

> Here is the error printed on MSYS2:
> 
> ```
> $ ./mach build
> Traceback (most recent call last):
>   File "./mach", line 148, in <module>
>     main(sys.argv[1:])
>   File "./mach", line 80, in main
>     sys.exit(mach.run(args))
>   File "C:/build/python/mach/mach/main.py", line 347, in run
>     self._print_error_header(argv, sys.stdout)
>   File "C:/build/python/mach/mach/main.py", line 479, in _print_error_header
>     fh.write('Error running mach:\n\n')
> LookupError: unknown encoding: cp65001
> ```
> 
> I have Python 2 (mingw-w64-x86_64-python2) installed.

**Comment by roytam1** [comment]
> LookupError: unknown encoding: cp65001

you need to turn off UTF-8 setting in non-Unicode codepage setting.

**Comment by 3oheicrw** [comment]
It seems I found the problem. Mozilla Build shell even though based on MSYS2 but not really behave like MSYS2 shell. Winlibs.com's GCC is a pure Win32 application (doesn't link with either cygwin-1.dll or msys-2.0.dll) so it doesn't support nor understand POSIX paths like /usr/include and so on. This is the reason why the configuration always stuck with errors. It seems you can't use Mozilla Build with Winlibs.com's GCC to build it at all.

**Comment by 3oheicrw** [comment]
Why I discovered this? Because I tried to build the FOX toolkit with Winlibs.com's GCC and Mozilla Build shell. The configuration is done but the compilation failed very quickly and it gives a very clear error message: fatal error: no input files.

**Comment by 3oheicrw** [comment]
> > LookupError: unknown encoding: cp65001
> 
> you need to turn off UTF-8 setting in non-Unicode codepage setting.

Well, I will try it again.

**Comment by 3oheicrw** [comment]
> It seems I found the problem. Mozilla Build shell even though based on MSYS2 but not really behave like MSYS2 shell. Winlibs.com's GCC is a pure Win32 application (doesn't link with either cygwin-1.dll or msys-2.0.dll) so it doesn't support nor understand POSIX paths like /usr/include and so on. This is the reason why the configuration always stuck with errors. It seems you can't use Mozilla Build with Winlibs.com's GCC to build it at all.

Almost forgot, the Mozilla Build shell we are using is based on MSYS 1.0, but I think it's the same as the MSYS2 shell.

**Comment by 3oheicrw** [comment]
@roytam1 Another error. These python2 scripts are full of errors.

```
Error running mach:

    ['configure']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

WindowsError: [Error 193] %1 is not a valid Win32 application

  File "C:/msys64/home/Administrator/Arctic-Fox/python/mozbuild/mozbuild/base.py", line 637, in __init__
    detect_virtualenv_mozinfo=detect_virtualenv_mozinfo)
  File "C:/msys64/home/Administrator/Arctic-Fox/python/mozbuild/mozbuild/base.py", line 165, in from_environment
    config = loader.read_mozconfig(mozconfig, moz_build_app=current_project)
  File "C:/msys64/home/Administrator/Arctic-Fox/python/mozbuild/mozbuild/mozconfig.py", line 232, in read_mozconfig
    cwd=self.topsrcdir, env=env)
  File "C:/msys64/mingw64/lib/python2.7/subprocess.py", line 217, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:/msys64/mingw64/lib/python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:/msys64/mingw64/lib/python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
```

**Comment by roytam1** [comment]
> @roytam1 Another error. These python2 scripts are full of errors.
> 
> ```
> Error running mach:
> 
>     ['configure']
> 
> The error occurred in code that was called by the mach command. This is either
> a bug in the called code itself or in the way that mach is calling it.
> 
> You should consider filing a bug for this issue.
> 
> If filing a bug, please include the full output of mach, including this error
> message.
> 
> The details of the failure are as follows:
> 
> WindowsError: [Error 193] %1 is not a valid Win32 application
> ```

try with `mach build` directly.

**Comment by 3oheicrw** [comment]
> > @roytam1 Another error. These python2 scripts are full of errors.
> > ```
> > Error running mach:
> > 
> >     ['configure']
> > 
> > The error occurred in code that was called by the mach command. This is either
> > a bug in the called code itself or in the way that mach is calling it.
> > 
> > You should consider filing a bug for this issue.
> > 
> > If filing a bug, please include the full output of mach, including this error
> > message.
> > 
> > The details of the failure are as follows:
> > 
> > WindowsError: [Error 193] %1 is not a valid Win32 application
> > ```
> 
> try with `mach build` directly.

Same error. Both ./mach configure and ./mach build

**Comment by 3oheicrw** [comment]
There is no time to sit here debugging these python2 scripts. Let's forget it and use MSVC.
