### PR TITLE
Avoid -DHUNSPELL_STATIC when using system hunspell

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by catap** [comment]
It fixes https://github.com/rmottola/Arctic-Fox/issues/208

**Comment by rmottola** [comment]
However Firefox kept that in esr52 and esr60 - I wonder if this hack is needed on OpenBSD for those if somebody still compiles them?
It was removed - without explicitely saying to remove static - in : [Bug 1463637](https://github.com/mozilla/gecko-dev/commit/c4035f104c1e5a6dfd8f56bbfc9c30ca81810612)

**Comment by catap** [comment]
With this fix I was able to build artic-fox on OpenBSD -current/amd64 with config:
```
export CC="clang"
export CXX="clang++"
export LDFLAGS="-Wl,-zwxneeded"

mk_add_options MOZ_MAKE_FLAGS="-s -j2"

ac_add_options --disable-crashreporter
ac_add_options --disable-tests
ac_add_options --disable-debug
ac_add_options --disable-updater
ac_add_options --enable-mozril-geoloc
ac_add_options --disable-webrtc
ac_add_options --disable-safe-browsing
ac_add_options --disable-parental-controls
ac_add_options --enable-release
ac_add_options --disable-necko-wifi
ac_add_options --disable-eme
ac_add_options --disable-gamepad
ac_add_options --enable-dbus
ac_add_options --disable-gio
ac_add_options --disable-pulseaudio
ac_add_options --enable-strip
ac_add_options --enable-install-strip
ac_add_options --enable-application=browser
ac_add_options --with-branding=browser/branding/arcticfox
ac_add_options --enable-optimize="-O0 -g3"
ac_add_options --enable-default-toolkit=cairo-gtk2
ac_add_options --disable-precompiled-startupcache
ac_add_options --enable-system-hunspell
```

Maybe in openbsd config two things should be changed?
1. Uncomment `--enable-system-hunspell`
2. Add `-O0 -g3` as optimization flags because it crashes without it, indeed.

**Comment by catap** [comment]
> However Firefox kept that in esr52 and esr60 - I wonder if this hack is needed on OpenBSD for those if somebody still compiles them? It was removed - without explicitely saying to remove static - in : [Bug 1463637](https://github.com/mozilla/gecko-dev/commit/c4035f104c1e5a6dfd8f56bbfc9c30ca81810612)

I think that the same hack possible required for someone who compiles old Firefox on new OpenBSD.

I also think that the root cause is new LLVM, and not OpenBSD. But, who knows and I a bit lazy to dig into rootcause.

**Comment by rmottola** [comment]
-O0 is very very slow... last time I tried, -O1 was enough, with -O2 sometimes working sometimes not.
On GCC there are some specific optimisations which needs to be disabled, but also that only on certain systems, e.g. on linux gcc14 just works.
you can try standard setup with  "ac_add_options --enable-optimize" without further specifying

**Comment by catap** [comment]
> you can try standard setup with "ac_add_options --enable-optimize" without further specifying

It crashes on start.

**Comment by catap** [comment]
Hm, I just rebuild it with `ac_add_options --enable-optimize="-g3"` and it works

**Comment by catap** [comment]
> However Firefox kept that in esr52 and esr60 - I wonder if this hack is needed on OpenBSD for those if somebody still compiles them? It was removed - without explicitely saying to remove static - in : [Bug 1463637](https://github.com/mozilla/gecko-dev/commit/c4035f104c1e5a6dfd8f56bbfc9c30ca81810612)

I just backported that patch into master as https://github.com/catap/Arctic-Fox/commit/8857ed1e3ebacdf05e3cd151807e93c3bc35de10, and it fails the same way:
```
 0:36.18 /usr/include/c++/v1/locale:2827:22: error: no member named 'HunspellAllocator' in namespace 'std'; did you mean simply 'HunspellAllocator'?
 0:36.18     _Tp* __t = (_Tp*)std::realloc(__owns ? __b.get() : 0, __new_cap);
 0:36.18                      ^
 0:36.18 /home/catap/src/Arctic-Fox/extensions/spellcheck/hunspell/glue/mozHunspellAllocator.h:12:7: note: 'HunspellAllocator' declared here
 0:36.18 class HunspellAllocator : public mozilla::CountingAllocatorBase<HunspellAllocator>
 0:36.19       ^
 0:36.19 libembedding_components_commandhandler.a.desc
 0:36.19 1 error generated.
 0:36.19 
```

**Comment by rmottola** [comment]
> Hm, I just rebuild it with `ac_add_options --enable-optimize="-g3"` and it works

that way you are optimizing nothing... I did test quite a bit on 7.4 and there -O1 was feasible

**Comment by rmottola** [comment]
> > However Firefox kept that in esr52 and esr60 - I wonder if this hack is needed on OpenBSD for those if somebody still compiles them? It was removed - without explicitely saying to remove static - in : [Bug 1463637](https://github.com/mozilla/gecko-dev/commit/c4035f104c1e5a6dfd8f56bbfc9c30ca81810612)
> 
> I just backported that patch into master as [catap@8857ed1](https://github.com/catap/Arctic-Fox/commit/8857ed1e3ebacdf05e3cd151807e93c3bc35de10), and it fails the same way:
> 
> ```
>  0:36.18 /usr/include/c++/v1/locale:2827:22: error: no member named 'HunspellAllocator' in namespace 'std'; did you mean simply 'HunspellAllocator'?
>  0:36.18     _Tp* __t = (_Tp*)std::realloc(__owns ? __b.get() : 0, __new_cap);
>  0:36.18                      ^
>  0:36.18 /home/catap/src/Arctic-Fox/extensions/spellcheck/hunspell/glue/mozHunspellAllocator.h:12:7: note: 'HunspellAllocator' declared here
>  0:36.18 class HunspellAllocator : public mozilla::CountingAllocatorBase<HunspellAllocator>
>  0:36.19       ^
>  0:36.19 libembedding_components_commandhandler.a.desc
>  0:36.19 1 error generated.
>  0:36.19 
> ```

oh, so it apparently doesn't fix....
I have an issue on FreeBSD with realloc - https://github.com/rmottola/Arctic-Fox/issues/212

**Comment by catap** [comment]
Yeah, and as I point at https://github.com/rmottola/Arctic-Fox/issues/208#issuecomment-2275616126 the LLVM triggers an issue.

The most interesting questions is why such issue hadn't happened in firefox at the first place.

**Comment by rmottola** [comment]
> Yeah, and as I point at [#208 (comment)](https://github.com/rmottola/Arctic-Fox/issues/208#issuecomment-2275616126) the LLVM triggers an issue.
> 
> The most interesting questions is why such issue hadn't happened in firefox at the first place.

Indeed, that is a good point, why doesn't it happen in firefox? it is still static in latest version, so how is eg. building of seamonkey and firefox esr115 version working!

I backported a patch that should ensure system library gets used, but it doesn't. I I suppose "glue" is still needed^ how do you understand it?

**Comment by catap** [comment]
@rmottola well... with git bisect and some time it is possible to discover when the build was fixed. If I recall right, they simple removes the code with this defines :) No defines, no problems.

**Comment by rmottola** [comment]
@catap  if you like to try? I don't build current Firefox myself.

I think the issue might be in here:
https://github.com/rmottola/Arctic-Fox/blob/master/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h

So I found potentially this commit could be the "fix":
https://github.com/mozilla/gecko-dev/commit/aadb1612e71c211c6713c52e0888985af3e6b034

but I can't backport it because we have no mozmemory.h available when building hunspell... may need some other bits.

https://github.com/rmottola/Arctic-Fox/blob/master/memory/build/moz.build

shows it is exported though...

**Comment by catap** [comment]
Unfortently I also doesn't build firefox, and I have no idea how to build it.

Regarding your commit: I doubt that it will help because an issue is define itself, which replaces `realloc` inside `std::realloc` into `std::HunspellAllocator::CountingRealloc` inside some C++ headers.

The rigth fix is move away from enforcing this via `-include .../mozilla-config.h` and add it only after all system's headers is included.

Another way which may work is create a weapper functions like `std::HunspellAllocator::CountingRealloc`...

**Comment by rmottola** [comment]
@catap worth investigating though, because read around and fixes maybe undefs and swizzling header orders and we know current firefox has no issues, so a backport might be worth.
Interesting is that on linux with gcc - where I have no issues however - I am able to use the patch. Look

```
% find . -name mozmemory.h
./memory/build/mozmemory.h
./obj-x86_64-pc-linux-gnu/dist/include/mozmemory.h
```

On FreeBSD the file is not included in obj-dir, clear it does not get found:
```
% find . -name mozmemory.h
./memory/build/mozmemory.h
```

You might check on OpenBSD? Maybe the build order is different or it doens't get properly exported.. wonder why?

Further check shows `MOZ_MEMORY` being enabled on my Linux build:
`obj-x86_64-pc-linux-gnu/dist/include/mozilla-config.h:#define MOZ_MEMORY 1`

**Comment by catap** [comment]
@rmottola I do have only one `mozmemory.h`, like you on FreeBSD.

I've tried this chnages:
```diff
--- a/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h
+++ b/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h
@@ -47,9 +47,10 @@
  * allocated using C memory allocation functions.
  */
 
-#include "mozilla/mozalloc.h"
 #include "mozHunspellAllocator.h"
 
+#include "mozmemory.h"
+
 #define malloc(size) HunspellAllocator::CountingMalloc(size)
 #define calloc(count, size) HunspellAllocator::CountingCalloc(count, size)
 #define free(ptr) HunspellAllocator::CountingFree(ptr)

```
which is similar with https://github.com/mozilla/gecko-dev/commit/aadb1612e71c211c6713c52e0888985af3e6b034

And it fails as:
```
 1:00.10 In file included from /home/catap/src/Arctic-Fox/obj-amd64-unknown-openbsd7.6/mozilla-config.h:194:
 1:00.10 /home/catap/src/Arctic-Fox/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h:52:10: fatal error: 'mozmemory.h' file not found
 1:00.10 #include "mozmemory.h"
 1:00.10          ^~~~~~~~~~~~~
```

**Comment by rmottola** [comment]
@catap so OpenBSD like FreeBSD here. Did you check the file, like I did in https://github.com/rmottola/Arctic-Fox/pull/211#issuecomment-2368683386 ? something is different in the build system.

I insist here, because reading bugzilla, this could be the fix, it fixes a very similar error on memory redefines!

**Comment by catap** [comment]
```
Arctic-Fox $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Arctic-Fox $ env AUTOCONF_VERSION=2.13 ./mach build                              
...
 0:42.29 gmake[4]: *** Waiting for unfinished jobs....
 0:42.29 2 warnings generated.
 0:42.29 liblayout_xul.a.desc
 0:42.29 gmake[3]: *** [/home/catap/src/Arctic-Fox/config/recurse.mk:33: compile] Error 2
 0:42.29 gmake[2]: *** [/home/catap/src/Arctic-Fox/config/rules.mk:540: default] Error 2
 0:42.29 gmake[1]: *** [/home/catap/src/Arctic-Fox/client.mk:411: realbuild] Error 2
 0:42.29 gmake: *** [client.mk:168: build] Error 2
 0:42.31 547 compiler warnings present.
Arctic-Fox $ Arctic-Fox $ find . -name mozmemory.h
./memory/build/mozmemory.h
Arctic-Fox $ find . -name mozilla-config.h
./obj-amd64-unknown-openbsd7.6/dist/include/mozilla-config.h
./obj-amd64-unknown-openbsd7.6/mozilla-config.h
Arctic-Fox $ grep MOZ_MEMORY ./obj-amd64-unknown-openbsd7.6/dist/include/mozilla-config.h
Arctic-Fox $ grep MOZ_MEMORY ./obj-amd64-unknown-openbsd7.6/mozilla-config.h  
Arctic-Fox $ 
```

So, nothing.

**Comment by rmottola** [comment]
@catap I think what you see is the issue why this fix doesn't apply! But.... why I don't know.

**Comment by rmottola** [comment]
it pisses me off that two BSDs are broken...  but the issue here is Clang and is libc++...  Disliked it. On FreeBSD gcc13 fails because it misses arc4random (old issue, that's why I used system clang). gcc14 instead fails configure tests... which I wonder, it works on Linux!!
You could try your luck on OpenBSD.

**Comment by catap** [comment]
@rmottola yeah, building firefox is mess. It was mess, and it is mess now :(

**Comment by rmottola** [comment]
@catap I tried again on 7.5 i386. Clang fails with the known error, gcc with

```
127:40.50     INPUT("StaticXULComponentsEnd/StaticXULComponentsEnd.o")
127:40.50 
127:40.50 ld: error: undefined hidden symbol: arc4random
127:40.50 >>> referenced by jsmath.cpp
```

which is exactly as FreeBSD. So perhaps if we had one fix, it would be catch all.

**Comment by rmottola** [comment]
@catap gcc builds are now pretty reliable for me! did you try? arc4random issue fixed...  AF running decently here!

**Comment by catap** [comment]
not yet, but I will. Thanks for ping!

**Comment by rmottola** [comment]
I'd say this branch is obsolete

**Comment by catap** [comment]
Quite possible, and as far as I recall you had found cleaner way.

**Comment by rmottola** [comment]
@catap true, it was using GCC... but things change... new release is out today. Testing on OpenBSD and FreeBSD will get on for me next week. It would make using clang also interesting, since it works on Mac (just tried today, but only up to clang 7 there). If you are still interested, your're welcome to try.

**Comment by catap** [comment]
I've used 8bcea2d5141647eb18d9302e98bf5339d453a18f as local root and it fails as usual:
```
61:59.11 /usr/include/c++/v1/locale:2458:26: error: no member named 'moz_xrealloc' in namespace 'std'; did you mean simply 'moz_xrealloc'?                   
61:59.11  2458 |   _Tp* __t       = (_Tp*)std::realloc(__owns ? __b.get() : 0, __new_cap);                                                                   
61:59.11       |                          ^~~~~                                                                                                              
61:59.11 /home/catap/src/Arctic-Fox/obj-amd64-unknown-openbsd7.8/dist/include/mozilla/mozalloc.h:91:16: note: 'moz_xrealloc' declared here                   
61:59.11    91 | MFBT_API void* moz_xrealloc(void* ptr, size_t size)                                                                                         
61:59.11       |                ^                                                                                                                            
61:59.11 1 error generated.                                                                                                                                  
```

**Comment by rmottola** [comment]
@catap  darn... which compiler? did you try gcc ?

**Comment by catap** [comment]
@rmottola with gcc-8 it builds and works on OpenBSD-7.8 which is beta right now.

So, the only issue is compatibility with modern libc++

**Comment by catap** [comment]
@rmottola and I was able to build it by clang on OpenBSD with this patch:
```
diff --git a/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h b/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h
index 729e66b8ef3b..04b78d03ed76 100755
--- a/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h
+++ b/extensions/spellcheck/hunspell/glue/hunspell_alloc_hooks.h
@@ -31,6 +31,17 @@
  *
  ******* END LICENSE BLOCK *******/
 
+/* LLVM 16 brings regression which brokes replacement
+ * malloc/calloc/realloc by macroses because it uses std:realloc.
+ * Disable replacment to overstep this issue.
+ */
+#ifdef __cplusplus
+#include <version>
+#if defined(_LIBCPP_VERSION) && _LIBCPP_VERSION >= 160000
+#define alloc_hooks_h__
+#endif
+#endif
+
 #ifndef alloc_hooks_h__
 #define alloc_hooks_h__
 
diff --git a/gfx/graphite2/src/MozGrMalloc.h b/gfx/graphite2/src/MozGrMalloc.h
index acaae1236c49..005deae228e5 100755
--- a/gfx/graphite2/src/MozGrMalloc.h
+++ b/gfx/graphite2/src/MozGrMalloc.h
@@ -3,6 +3,18 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/.
  */
 
+
+/* LLVM 16 brings regression which brokes replacement
+ * malloc/calloc/realloc by macroses because it uses std:realloc.
+ * Disable replacment to overstep this issue.
+ */
+#ifdef __cplusplus
+#include <version>
+#if defined(_LIBCPP_VERSION) && _LIBCPP_VERSION >= 160000
+#define MOZ_GR_MALLOC_H
+#endif
+#endif
+
 #ifndef MOZ_GR_MALLOC_H
 #define MOZ_GR_MALLOC_H
 
```
and it can open this issue!

**Comment by catap** [comment]
If you ok with it, I can open PR to finally fix it.

**Comment by rmottola** [comment]
> @rmottola with gcc-8 it builds and works on OpenBSD-7.8 which is beta right now.
> 
> So, the only issue is compatibility with modern libc++

I can build with gcc 11 on OpenBSD 7.7, but not with clang, same failure as you.

GCC 11 isn't "new" enough to have a modern libc++? I do wonder

On linux I am compiling with gcc 14.3 even

**Comment by rmottola** [comment]
Hmm, it is worth a try... attach a patch as a file here?

**Comment by rmottola** [comment]
I still don't like that we need a hack that I can't find in firefox.

Would you mind looking at these:

https://github.com/mozilla/gecko-dev/commit/c4035f104c1e5a6dfd8f56bbfc9c30ca81810612

https://github.com/mozilla/gecko-dev/commit/aadb1612e71c211c6713c52e0888985af3e6b034

**Comment by rmottola** [comment]
for Graphite instead I found this.

https://github.com/mozilla/gecko-dev/commit/f753366a3e88e80afc7b5fecd732b6eb02d49dea

I still want to support gcc 4.8 if possible, so I need to perhaps conditionally define them or test if perhaps they aren't actually needed. Needs some more work.

**Comment by rmottola** [comment]
#286 to gather these commits to backport and check on different compiler configurations.

**Comment by catap** [comment]
@rmottola sorry, I've used poor wording. I mean new enough LLVM's libc++, not just "new enough libc++".

FYI: I had imported in august gcc-15 into OpenBSD ports tree and will try hard enough to switch OpenBSD to gcc 15 after release.

I doubt that you'll find any nice fix for huspell, because it was removed as far as I understand.

**Comment by catap** [comment]
I just tried:

https://github.com/mozilla/gecko-dev/commit/f753366a3e88e80afc7b5fecd732b6eb02d49dea 
https://github.com/mozilla/gecko-dev/commit/c4035f104c1e5a6dfd8f56bbfc9c30ca81810612
https://github.com/mozilla/gecko-dev/commit/aadb1612e71c211c6713c52e0888985af3e6b034

as https://github.com/catap/Arctic-Fox/tree/openbsd but I can't build it because seems that I had resolved some conflicts in the wrong way.

I'll try one more attempt in a few days, but if you have capacity to prepare a branch which I may test, I'll be appricieted and do it.

**Comment by catap** [comment]
@rmottola long story short: it still includes hunspell_alloc_hooks.h and code below brokes the build:

```
#define malloc(size) HunspellAllocator::CountingMalloc(size)
#define calloc(count, size) HunspellAllocator::CountingCalloc(count, size)
#define free(ptr) HunspellAllocator::CountingFree(ptr)
#define realloc(ptr, size) HunspellAllocator::CountingRealloc(ptr, size)
```

**Comment by rmottola** [comment]
@catap on FreeBSD I had to remain with GCC 13, I had issues with GCC 14, while it works on linux. Things are complicated

I imported the patch that appears to fix realloc stuff in Graphite for FreeBSD/clang - it still works on Linux/gcc . But I need to test FreeBSD/gcc before giving it green light. It is in dev.

Hunspell is more stubborn, but maybe the fix could be brought over.. watch #286

**Comment by catap** [comment]
Thanks, I had subscribed to this issue. Feel free to ping me when :)

Also, I think that it is the right step to support modern clang with modern llvm's libc++ because it is a kind of standard and I expect that similar chnages (adding `std::`) may happens in gcc as well.
