### ISSUE TITLE
JS Bot Detectors

### ISSUE THREAD

**Issue by rmottola** [rmottola/Arctic-Fox#321]
We know some websites are not accessible because they use bot detectors, but these break on older or non-mainstream browsers. Here an Umbrella bug to keep track of them:

### CloudFlare
Too high JS requirements. Doesn't work on SeaMonkey either. Little hope to get it fixed easily

### FastLy
Works.

### go-away
Too high JS requirements. Doesn't work on SeaMonkey either. Little hope to get it fixed easily

### Anubis
Does not work, hangs. Works on SeaMonkey, so there is hope.

**Comment by carlosgonz0** [comment]
I started debugging on x86: ./arcticfox --jsconsole on invidious js bot failed.

```

          1779120064524	Toolkit.Telemetry	ERROR	TelemetryEnvironment::_isDefaultBrowser - Could not determine if default browser: [Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: resource://gre/modules/XPCOMUtils.jsm :: XPCU_serviceLambda :: line 230"  data: no] Stack trace: XPCU_serviceLambda()@resource://gre/modules/XPCOMUtils.jsm:230 < XPCU_defineLazyGetter/<.get()@resource://gre/modules/XPCOMUtils.jsm:198 < get()@resource:///modules/ShellService.jsm:106 < isDefaultBrowser()@resource:///modules/ShellService.jsm:90 < EnvironmentCache.prototype._isDefaultBrowser()@resource://gre/modules/TelemetryEnvironment.jsm:1140 < EnvironmentCache.prototype._updateSettings()@resource://gre/modules/TelemetryEnvironment.jsm:1177 < EnvironmentCache()@resource://gre/modules/TelemetryEnvironment.jsm:767 < getGlobal()@resource://gre/modules/TelemetryEnvironment.jsm:58 < this.TelemetryEnvironment.registerChangeListener()@resource://gre/modules/TelemetryEnvironment.jsm:77 < TelemetryStartup.prototype.observe()@TelemetryStartup.js:32  Log.jsm:753
shellService not found in ShellService: undefined
OpenGL compositor Initialized Succesfully.
Version: 4.6 (Compatibility Profile) Mesa 26.0.3-1ubuntu1
Vendor: AMD
Renderer: AMD Radeon HD 7700 Series (radeonsi, verde, ACO, DRM 3.64, 7.0.0-14-generic)
FBO Texture Target: TEXTURE_2D
OpenGL compositor Initialized Succesfully.
Version: 4.6 (Compatibility Profile) Mesa 26.0.3-1ubuntu1
Vendor: AMD
Renderer: AMD Radeon HD 7700 Series (radeonsi, verde, ACO, DRM 3.64, 7.0.0-14-generic)
FBO Texture Target: TEXTURE_2D
shellService not found in ShellService: undefined
OpenGL compositor Initialized Succesfully.
Version: 4.6 (Compatibility Profile) Mesa 26.0.3-1ubuntu1
Vendor: AMD
Renderer: AMD Radeon HD 7700 Series (radeonsi, verde, ACO, DRM 3.64, 7.0.0-14-generic)
FBO Texture Target: TEXTURE_2D
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” browser.xul
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified  (unknown)
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead. (unknown)
SyntaxError: expected expression, got '?'[Learn More]  search:131:8135
XML Parsing Error: no root element found
Location: https://h.clarity.ms/collect
Line Number 1, Column 1:  collect:1:1
downloadable font: download failed (font-family: "Jost" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: https://invidious.io/css/fonts/vendor/jost/jost-v4-latin-regular.woff2  main.css:6:42805
downloadable font: download failed (font-family: "Jost" style:normal weight:bold stretch:normal src index:1): status=2147746065 source: https://invidious.io/css/fonts/vendor/jost/jost-v4-latin-700.woff2  main.css:6:43269
downloadable font: download failed (font-family: "Jost" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: https://invidious.io/css/fonts/vendor/jost/jost-v4-latin-regular.woff  main.css:6:42805
downloadable font: download failed (font-family: "Jost" style:normal weight:bold stretch:normal src index:2): status=2147746065 source: https://invidious.io/css/fonts/vendor/jost/jost-v4-latin-700.woff  main.css:6:43269
Empty string passed to getElementById().  instances:1766:11
TypeError: r.text is not a function[Learn More]  bundle.79ae519e.min.js:14:41308
SyntaxError: missing ( before catch  _helpers.js:1:2426
ReferenceError: helpers is not defined[Learn More]  themes.js:1:946
The video on this page can’t be played. Your system may not have the required video codecs for: audio/mp4, video/mp4
```

``` SyntaxError: expected expression, got '?' [Learn More]  search:131:8135```, so looks like Goanna dont know: ?, SO JIT FAILED HERE FIRSTLY.

```The video on this page can’t be played. Your system may not have the required video codecs for: audio/mp4, video/mp4```, next issue.

**Comment by carlosgonz0** [comment]
So Invidious is using  microsoft opensource clarity for js bot:
https://github.com/microsoft/clarity

```
XML Parsing Error: no root element found
Location: https://h.clarity.ms/collect
Line Number 1, Column 1:  collect:1:1

```
Full shame IMHO.

**Comment by Matias314** [comment]
CloudFlare works in White Star on OS X 10.5.8 PowerPC and maybe with the PPC64 Linux build as well (I haven't tested). Perhaps you could have a look at what it's doing. But it will be quite slow on a G4, even on a G5 it takes a minute or two.

> So Invidious is using microsoft opensource clarity for js bot

Not every Invidious instance uses bot detection so this statement is false.

**Comment by OwnedByWuigi** [comment]
CloudFlare disables certain checks if it detects you have a Pale Moon useragent. Set a useragent override for *.cloudflare.com and have the useragent be set to Pale Moon's.

E.g this is how Dactyloidae 13.2 handles it:
`
// Special-case Cuckflare
// With Dactyloidae useragent they send a challenge that fucks up the browser JS system. So we fake PM.
pref("@GUAO_PREF@.cloudflare.com","Mozilla/5.0 (%OS_SLICE% rv:@UXP_VERSION@) @UXP_DATE_SLICE@ @PALE_MOON_SLICE@");
`

**Comment by rmottola** [comment]
> CloudFlare disables certain checks if it detects you have a Pale Moon useragent. Set a useragent override for *.cloudflare.com and have the useragent be set to Pale Moon's.
> 
> E.g this is how Dactyloidae 13.2 handles it: `// Special-case Cuckflare // With Dactyloidae useragent they send a challenge that fucks up the browser JS system. So we fake PM. pref("@GUAO_PREF@.cloudflare.com","Mozilla/5.0 (%OS_SLICE% rv:@UXP_VERSION@) @UXP_DATE_SLICE@ @PALE_MOON_SLICE@");`

I tried as a test, but it didn't help much. I could keep it in so everybody can hack.
What exact string do you spit out? (get it from about:config)

I get:
```
Timestamp: 07/08/26 10:38:10
Error: ReferenceError: ResizeObserver is not defined
Source File: https://plausible.io/js/script.js
Line: 1
```

Suppose AF's JS APIs are still not enough.

**Comment by rmottola** [comment]
> > CloudFlare disables certain checks if it detects you have a Pale Moon useragent. Set a useragent override for *.cloudflare.com and have the useragent be set to Pale Moon's.
> > E.g this is how Dactyloidae 13.2 handles it: `// Special-case Cuckflare // With Dactyloidae useragent they send a challenge that fucks up the browser JS system. So we fake PM. pref("@GUAO_PREF@.cloudflare.com","Mozilla/5.0 (%OS_SLICE% rv:@UXP_VERSION@) @UXP_DATE_SLICE@ @PALE_MOON_SLICE@");`
> 
> I tried as a test, but it didn't help much. I could keep it in so everybody can hack. What exact string do you spit out? (get it from about:config)
> 
> I get:
> 
> ```
> Timestamp: 07/08/26 10:38:10
> Error: ReferenceError: ResizeObserver is not defined
> Source File: https://plausible.io/js/script.js
> Line: 1
> ```

But when retrying I get things like:

```
Timestamp: 07/08/26 10:43:24
Error: Content Security Policy: The page’s settings blocked the loading of a resource at https://www.feabie.com/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=a17dcaac8f11cd47 (“script-src 'nonce-uzaRVG7Y8C7zhnn1bGxzMQ' 'unsafe-eval' https://challenges.cloudflare.com”).
```

I wonder why it is not deterministic and gets to CSP now. Perhaps AF bug there.

**Comment by OwnedByWuigi** [comment]
This is the exact string I use to make Dactyloidae pass (most) CF checks.


`Mozilla/5.0 (Windows NT 10.0; rv:4.8) Goanna/20170101 PaleMoon/34.3.1`

Some sites still have issues, but sites like betawiki.net work fine after this.

**Comment by OwnedByWuigi** [comment]
@rmottola what do you get with Anubis? That seems easier to backport from Pale Moon.

**Comment by rmottola** [comment]
> [@rmottola](https://github.com/rmottola) what do you get with Anubis? That seems easier to backport from Pale Moon.

interesting is that accessing https://anubis.techaro.lol/ works fine with ArcticFox, but has issues when used in other websites. It could be a different issue, I am not sure.

**Comment by OwnedByWuigi** [comment]
> interesting is that accessing https://anubis.techaro.lol/ works fine with ArcticFox, but has issues when used in other websites. It could be a different issue, I am not sure.

Sites like https://repo.palemoon.org use a difficulty level of 4 (not difficult) (sometimes it is 2 but it really varies for me)

Meanwhile a site like https://thereisonlyxul.org/ has a difficulty level of 2 (more difficult).

I'd assume difficulty level 4 would pass but 2 would not.

**Comment by rmottola** [comment]
> > interesting is that accessing https://anubis.techaro.lol/ works fine with ArcticFox, but has issues when used in other websites. It could be a different issue, I am not sure.
> 
> Sites like https://repo.palemoon.org use a difficulty level of 4 (not difficult) (sometimes it is 2 but it really varies for me)
> 
> Meanwhile a site like https://thereisonlyxul.org/ has a difficulty level of 2 (more difficult).
> 
> I'd assume difficulty level 4 would pass but 2 would not.

Interesting is that neither of those above does work on current ArcticFox, I don't see errors in console either. Anubis itself is running 1.26 beta, maybe they did some compatibility fixes?

**Comment by OwnedByWuigi** [comment]
Re-visiting this, I may have a clue as to why specifically Anubis doesn't work. Will update soon.

**Comment by Xe** [comment]
Can you get the output of https://halone.within.lgbt/known-good/arctic-fox with Arctic Fox on a few hosts with a few different OSes and CPU architectures and paste the output somewhere? I don't need IP addresses, just the other headers so I can adjust default rules.

**Comment by Xe** [comment]
Can you add the tag `ArcticFox/version-number` to your User-Agent string so I can add a default rule for Arctic Fox in Anubis? I want to add this rule:

```yaml
- name: "reduce-weight-arcticfox"
  action: WEIGH
  weight:
    adjust: -5
  expression:
    all:
      - '"Accept" in headers'
      - '"Accept-Encoding" in headers'
      - 'headers["Accept-Encoding"].contains("gzip")'
      - 'headers["Accept-Encoding"].contains("deflate")'
      - 'headers["Accept-Encoding"].contains("br")'
      - '"X-Http-Protocol" in headers'
      - 'headers["X-Http-Protocol"] == "HTTP/2.0"'
      - userAgent.startsWith("Mozilla/")
      - userAgent.matches("ArcticFox/[^/ ]+")
```

But I can't because the User-Agent string doesn't let me match on Arctic Fox cleanly.

**Comment by rmottola** [comment]
@Xe ArcticFox gives out the version number, but it depends on how the user agent is set.

For current dev which will become v48.0:

Firefox compatibillity
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.9) Gecko/47.3 Firefox/52.9
X-Forwarded-For: 194.208.63.172
X-Forwarded-Host: halone.within.lgbt
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Http-Protocol: HTTP/2.0
X-Ja3n-Fingerprint: b44c7203d8b3f047e606e905ebbb7094
X-Ja4-Fingerprint: t12517d211_6d415d290621_a44194d81fde
X-Ja4h-Fingerprint: ge20nn05enus_5709c464a9cc_000000000000_000000000000
X-Ja4t-Fingerprint: 64256_4-1-8-1-3_1448_167
X-Real-Ip: 194.208.63.172
X-Request-Id: 019ff65f-cc1c-7589-9368-4b9d8fbe681b
X-Scheme: https
```

Gecko Compatibility:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.9) Gecko/20100101 Firefox/52.9 ArcticFox/48.0
X-Forwarded-For: 194.208.63.172
X-Forwarded-Host: halone.within.lgbt
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Http-Protocol: HTTP/2.0
X-Ja3n-Fingerprint: b44c7203d8b3f047e606e905ebbb7094
X-Ja4-Fingerprint: t12517d211_6d415d290621_a44194d81fde
X-Ja4h-Fingerprint: ge20nn06enus_588c0bd31528_000000000000_000000000000
X-Ja4t-Fingerprint: 64256_4-1-8-1-3_1448_167
X-Real-Ip: 194.208.63.172
X-Request-Id: 019ff660-a204-7425-a8f9-3c804f0122c3
X-Scheme: https
```

Native:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:47.3) Gecko/20100101 ArcticFox/48.0
X-Forwarded-For: 194.208.63.172
X-Forwarded-Host: halone.within.lgbt
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Http-Protocol: HTTP/2.0
X-Ja3n-Fingerprint: b44c7203d8b3f047e606e905ebbb7094
X-Ja4-Fingerprint: t12517d211_6d415d290621_a44194d81fde
X-Ja4h-Fingerprint: ge20nn06enus_588c0bd31528_000000000000_000000000000
X-Ja4t-Fingerprint: 64256_4-1-8-1-3_1448_167
X-Real-Ip: 194.208.63.172
X-Request-Id: 019ff661-eddf-727d-89ce-acfb6a05bede
X-Scheme: https
```

Except when disguised as Firefox, you should always be able to match ArcticFox and its version
